version: 2

updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Mexico_City
    open-pull-requests-limit: 5
    groups:
      dev-dependencies:
        dependency-type: development
        patterns:
          - pytest*
          - ruff
          - mypy
          - bandit
          - pre-commit
          - safety

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 3