[mypy]
python_version = 3.12
warn_return_any = True
warn_unused_configs = True
ignore_missing_imports = False
disallow_untyped_defs = False
check_untyped_defs = True
disallow_incomplete_defs = False

[mypy-aiogram.*]
ignore_missing_imports = True

[mypy-sqlalchemy.*]
ignore_missing_imports = True

[mypy-pytz.*]
ignore_missing_imports = True

[mypy-redis.*]
ignore_missing_imports = True