"""
Add manual_file_count to promotions table

Revision ID: 20250406_manual_file_count
Revises: c32861733e54
Create Date: 2026-04-06

Esta migración:
1. Agrega la columna manual_file_count (Integer, nullable)
2. Hace nullable la columna package_id en promotions
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20250406_manual_file_count'
down_revision: Union[str, None] = 'c32861733e54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Agregar columna manual_file_count
    op.add_column('promotions', sa.Column('manual_file_count', sa.Integer(), nullable=True))

    # Hacer package_id nullable
    # SQLite no permite ALTER COLUMN directamente, necesitamos recrear la tabla
    # o usar batch_alter_table
    with op.batch_alter_table('promotions', schema=None) as batch_op:
        batch_op.alter_column('package_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # SQLite necesita manejo especial para el downgrade
    # Primero manejar datos con package_id=NULL, luego hacer NOT NULL

    conn = op.get_bind()
    dialect = conn.dialect.name

    if dialect == 'sqlite':
        # En SQLite, batch_alter_table recrea la tabla completa
        # Necesitamos manejar los datos antes del ALTER
        _handle_null_package_ids(conn)

        # En SQLite, usamos batch_alter_table que recrea la tabla
        # Elimina manual_file_count y hace package_id NOT NULL en una operación
        with op.batch_alter_table('promotions', schema=None) as batch_op:
            batch_op.alter_column('package_id',
                   existing_type=sa.INTEGER(),
                   nullable=False)
            # No necesitamos drop_column explícito en SQLite
            # batch_alter_table recrea sin la columna que no está en el modelo
    else:
        # PostgreSQL y otros - operaciones estándar
        # Primero: manejar filas con package_id=NULL
        _handle_null_package_ids(conn)

        # Luego: eliminar la columna manual_file_count
        op.drop_column('promotions', 'manual_file_count')

        # Finalmente: hacer package_id NOT NULL
        with op.batch_alter_table('promotions', schema=None) as batch_op:
            batch_op.alter_column('package_id',
                   existing_type=sa.INTEGER(),
                   nullable=False)

    # ### end Alembic commands ###


def _handle_null_package_ids(conn):
    """Maneja las filas con package_id=NULL antes de hacerla NOT NULL."""
    # Verificar si existe algún paquete para usar como fallback
    result = conn.execute(sa.text("SELECT id FROM packages ORDER BY id LIMIT 1"))
    fallback_package = result.scalar()

    if fallback_package:
        # Asignar el package_id fallback a las promociones que lo necesiten
        conn.execute(
            sa.text("""
                UPDATE promotions
                SET package_id = :fallback_id
                WHERE package_id IS NULL
            """),
            {"fallback_id": fallback_package}
        )
    else:
        # No hay paquetes disponibles, eliminar promociones huérfanas
        # Esto es un caso extremo - normalmente debería haber al menos un paquete
        conn.execute(
            sa.text("""
                DELETE FROM promotion_interests
                WHERE promotion_id IN (
                    SELECT id FROM promotions WHERE package_id IS NULL
                )
            """)
        )
        conn.execute(
            sa.text("DELETE FROM promotions WHERE package_id IS NULL")
        )
