"""add_last_reference_id_to_mission_progress

Revision ID: 3f20074a2dd3
Revises: f7d08ca1ce1a
Create Date: 2026-04-07 14:05:49.447329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f20074a2dd3'
down_revision: Union[str, None] = 'f7d08ca1ce1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('broadcast_reactions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_broadcast_user_reaction'), type_='unique')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_categories_id'), ['id'], unique=False)

    with op.batch_alter_table('promotions', schema=None) as batch_op:
        batch_op.alter_column('is_vip_exclusive',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('user_mission_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_reference_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_mission_progress', schema=None) as batch_op:
        batch_op.drop_column('last_reference_id')

    with op.batch_alter_table('promotions', schema=None) as batch_op:
        batch_op.alter_column('is_vip_exclusive',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_id'))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)

    with op.batch_alter_table('broadcast_reactions', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_broadcast_user_reaction'), ['broadcast_id', 'user_id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
