"""Add anonymous_messages table for VIP anonymous messaging

Revision ID: 499b5924723f
Revises: add_selected_emoji_ids
Create Date: 2026-04-05 00:07:13.940209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '499b5924723f'
down_revision: Union[str, None] = 'add_selected_emoji_ids'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anonymous_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('UNREAD', 'READ', 'REPLIED', name='anonymousmessagestatus'), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_by', sa.BigInteger(), nullable=True),
    sa.Column('admin_reply', sa.Text(), nullable=True),
    sa.Column('replied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('anonymous_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_anonymous_messages_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_anonymous_messages_sender_id'), ['sender_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anonymous_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anonymous_messages_sender_id'))
        batch_op.drop_index(batch_op.f('ix_anonymous_messages_id'))

    op.drop_table('anonymous_messages')
    # ### end Alembic commands ###
