"""sync schema drift from models

Revision ID: 53f8f3496f23
Revises: c25b0020dcc5
Create Date: 2026-03-30 09:16:31.995943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53f8f3496f23'
down_revision: Union[str, None] = 'c25b0020dcc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite does not support ALTER TABLE for constraints; use create_index with unique=True instead
    op.create_index('uq_user_promotion_interest', 'promotion_interests', ['user_id', 'promotion_id'], unique=True)
    op.add_column('story_achievements', sa.Column('icon', sa.String(length=10), nullable=True))
    op.add_column('story_choices', sa.Column('choice_archetype', sa.Enum('SEDUCTOR', 'OBSERVER', 'DEVOTO', 'EXPLORADOR', 'MISTERIOSO', 'INTREPIDO', name='archetypetype'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('story_choices', 'choice_archetype')
    op.drop_column('story_achievements', 'icon')
    op.drop_index('uq_user_promotion_interest', 'promotion_interests')
    # ### end Alembic commands ###
