"""add_cooldown_hours_to_missions

Revision ID: 7c158f7483f5
Revises: 3f20074a2dd3
Create Date: 2026-04-07 14:19:38.962606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c158f7483f5'
down_revision: Union[str, None] = '3f20074a2dd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cooldown_hours', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.drop_column('cooldown_hours')

    # ### end Alembic commands ###
