"""add_cooldown_hours_to_missions

Revision ID: 7c158f7483f5
Revises: 3f20074a2dd3
Create Date: 2026-04-07 14:19:38.962606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c158f7483f5'
down_revision: Union[str, None] = '3f20074a2dd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    dialect = conn.dialect.name

    # Verificar si la columna cooldown_hours ya existe (idempotente)
    column_exists = False
    if dialect == 'sqlite':
        result = conn.execute(sa.text("PRAGMA table_info(missions)"))
        columns = [row[1] for row in result.fetchall()]
        column_exists = 'cooldown_hours' in columns
    else:
        result = conn.execute(sa.text("""
            SELECT EXISTS (
                SELECT FROM information_schema.columns
                WHERE table_name = 'missions' AND column_name = 'cooldown_hours'
            )
        """))
        column_exists = result.scalar()

    if not column_exists:
        with op.batch_alter_table('missions', schema=None) as batch_op:
            batch_op.add_column(sa.Column('cooldown_hours', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.drop_column('cooldown_hours')

    # ### end Alembic commands ###
